# Generated by Django 3.0.5 on 2022-03-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_imagerelated_id_alter_slider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerelated',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
