# Generated by Django 3.0.5 on 2022-04-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginrecord_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户详细信息', 'verbose_name_plural': '用户详细信息'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_phone_on',
            field=models.BooleanField(default=False, verbose_name='是否已经验证'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_on',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
