# Generated by Django 3.0.5 on 2022-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220405_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_phone_on',
            new_name='is_phone_valid',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_on',
            new_name='phone_no',
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='source',
            field=models.CharField(max_length=16, null=True, verbose_name='登录的来源'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='version',
            field=models.CharField(max_length=16, null=True, verbose_name='登录的版本'),
        ),
    ]
